# -*- coding: utf-8 -*-
"""DL1 : Churn Predn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19EpoeqDDit10bMlBKY_PIgs-zPbNdblb
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import tensorflow
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

df = pd.read_csv('/content/Churn_Modelling.csv')
df.info()

df['Gender'].value_counts()

df.drop(columns = ['RowNumber','CustomerId','Surname'],inplace=True)

df  = pd.get_dummies(data = df , columns=['Geography','Gender'],drop_first= True)

df

X = df.drop(columns=['Exited'])
y = df['Exited']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2 , random_state= 0)
X_train

scaler  = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

""" # **Hello**"""

pd.DataFrame(X_train_scaled, columns=X_train.columns)

model = Sequential()

model.add(Dense(11,activation='relu',input_dim=11))
model.add(Dense(11,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.summary()

model.compile(loss = 'binary_crossentropy',optimizer = 'Adam' , metrics = ['accuracy'])

history = model.fit(X_train_scaled,y_train,batch_size = 50 , epochs = 100 , verbose=1,validation_split=0.2)
history

y_pred = model.predict(X_test)

y_pred = y_pred.argmax(axis=-1)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)



plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

